# Generated by Django 4.2 on 2024-01-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='font',
            field=models.DateTimeField(null=True),
        ),
    ]
